### ISSUE TITLE
does not show thumbnail in production

### ISSUE THREAD

**Issue by maxxyryo** [dasundev/livewire-dropzone#14]
When using the package on local host the thumbnail appears, but when uploading the package to production the same gives an error in the link, can you help me with this?

**Comment by dasundev** [comment]
@maxxyryo What is the error are you encountering?

**Comment by maxxyryo** [comment]
the thumbnail of the temporary image does not appear
I have already given the following commands:
php artisan view:clear
php artisan route:clear
php artisan config:clear
php artisan cache:clear

and even so, when uploading, the thumbnail does not appear

**Comment by dcblogdev** [comment]
could it be that on production you need to link storage? `php artisan storage:link`

**Comment by dasundev** [comment]
> could it be that on production you need to link storage? `php artisan storage:link`

@maxxyryo you should do this.

Closing this issue.
