### ISSUE TITLE
Error when uploading more than 4 files at a time

### ISSUE THREAD

**Issue by kontramundo** [dasundev/livewire-dropzone#25]
if I want to load more than 4 files simultaneously it gives me this error:

VM9528:1 Uncaught SyntaxError: Unexpected token '<', "<br />
<b>"... is not valid JSON
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.<anonymous> (livewire.js?id=5d8beb2e:566:62)

**Comment by dasundev** [comment]
I've checked more than 10 files at once. It seems to work. No errors in the browser console.

**Comment by kontramundo** [comment]
Hello, I already managed to solve it, it was just an issue with the post_max_size. Just increase it.
Thank you
