### ISSUE TITLE
Class "Number" not found

### ISSUE THREAD

**Issue by tominal** [dasundev/livewire-dropzone#29]
Hey there,

Nice repo! I gave it a try and hit a snag similar to #17 :

![2024-04-24_00-17](https://github.com/dasundev/livewire-dropzone/assets/8497308/ab84fa27-160f-43d7-bbab-d28849e13866)

Not sure what Number helper class is used here but it's probably an easy fix by adding its namespace in there.

- PHP Version 8.1
- Laravel Version 10.32.1

**Comment by dasundev** [comment]
Did this happen when you published the dropzone view?

**Comment by dasundev** [comment]
Can you make a PR with the namespace?

**Comment by tominal** [comment]
Nope, just following the docs when installing it in a Livewire 3 project. Would you happen to remember what Number facade you used here? I don't see anything in the composer.json so that I can locate any namespace. -T

**Comment by dasundev** [comment]
```php

Illuminate\Support\Number

```

**Comment by tominal** [comment]
Got it! I created #30 and also found a second one of those in the  same file. Should fix it!
