### ISSUE TITLE
Improvement on dropzone blade file to allow multiple dropzone components on same page

### ISSUE THREAD

**Issue by Fsmash** [dasundev/livewire-dropzone#31]
This is a really straightforward issue. We have multiple livewire dropzone components on the same page. Even with "wire:key" the Alpine dropzone javascript does not dispatch the correct "{uuid}" event like with "fileRemoved".

This can easily be fix like so
![image](https://github.com/dasundev/livewire-dropzone/assets/11857985/dad1be1b-9847-4d56-850a-55d3518d0722)

Then the correct event can be dispatched like so
![image](https://github.com/dasundev/livewire-dropzone/assets/11857985/32bd2b12-189d-4950-839b-2eb4aa1d905d)

Such a minor change that it doesn't really call for a pull request. This is just what I did after publishing the blade file to get this to work for my use case. Setting uuid as a parameter to take in uniquely identifies the Alpine such that the right event gets dispatched. I feel like there is no downside to doing it this way and just gives people the option to add multiple livewire dropzone components on a single page. I need it for forms that are under different tabs on a page.

**Comment by dasundev** [comment]
Yeah, it's a bug. this should fixed in the repo. 

Can you make a PR?

**Comment by Fsmash** [comment]
Sure.
