### ISSUE TITLE
missing comma

### ISSUE THREAD

**Issue by gepopp** [dasundev/livewire-dropzone#33]
Hey there,
thx for that great component, love using it.

JFYI, since one of the latest versions uve got a misssing comma in the alpine data in the view file ( line 5 ) 

Have a nice day,
gerhard

**Comment by dasundev** [comment]
Oh, thanks for mentioning this. Can you quickly make a PR?

**Comment by gepopp** [comment]
PR?

**Comment by dasundev** [comment]
Yes, a pull request.

**Comment by Fsmash** [comment]
Noticed this myself after updating and publishing the views again. Can make a PR now.
