### ISSUE TITLE
error Class "Illuminate\Support\Number" not found

### ISSUE THREAD

**Issue by evokelektrique** [dasundev/livewire-dropzone#35]
Fresh install, using the example codes provided in README and I'm getting this error

```
<livewire:dropzone
        wire:model="banners"
        :rules="['image','mimes:png,jpeg','max:10420']"
        :multiple="true" />
```

```
PHP 8.1.3
laravel 10.19.0
Class "Illuminate\Support\Number" not found
```

**Comment by dasundev** [comment]
It seems that some developers are encountering issues with the `Number` facade.

There was a similar problem reported earlier, identified as issue #29, which I thought had been resolved.

For a temporary solution, you need to publish the view and update a line of code. Here's what you should do:

1. **Publish the view**: Run the following command in your terminal:

```bash
php artisan vendor:publish --tag=livewire-dropzone-views
```

This command will publish the view file where you can make the necessary changes.

2. **Change the line of code**: In the published view file (refer to [line 103](https://github.com/dasundev/livewire-dropzone/blob/ae9c984723b7485b9792b7501e4c700d39d25fbf/resources/views/livewire/dropzone.blade.php#L103C104-L103C161)), update:

```php
{{ \Illuminate\Support\Number::fileSize($file['size']) }}
```

to:

```php
{{ Number::fileSize($file['size']) }}
```
