### ISSUE TITLE
SOLUTION: count(): Argument #1 ($value) must be of type Countable|array, null given

### ISSUE THREAD

**Issue by casacarro** [dasundev/livewire-dropzone#43]
Hey!

I just found the solutions for this error. 
You just need to replace the line 84 for:
`@if($files &&count($files) > 0)`

Steps to reproduce the error:
- Using the livewire-dropzone inside a modal, when you try to close it, you get this error. So, you just need to validate if $files exists first.

Thanks!

**Comment by dasundev** [comment]
Please send a PR.

**Comment by casacarro** [comment]
Sent from my own account. Thanks
